/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */
package myNewPackage;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START_PROGRAM = 4;
  /** RegularExpression Id. */
  int END_PROGRAM = 5;
  /** RegularExpression Id. */
  int NUM = 9;
  /** RegularExpression Id. */
  int FLOAT_NUM = 10;
  /** RegularExpression Id. */
  int LETRA = 11;
  /** RegularExpression Id. */
  int TIPO = 12;
  /** RegularExpression Id. */
  int OPERADOR_MATEMATICO = 13;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO = 14;
  /** RegularExpression Id. */
  int BLOCO_INICIO = 15;
  /** RegularExpression Id. */
  int BLOCO_FINAL = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int THEN = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int FOR = 20;
  /** RegularExpression Id. */
  int TO = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int HERDA = 23;
  /** RegularExpression Id. */
  int RETURN = 24;
  /** RegularExpression Id. */
  int CLASS = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"PRINCIPAL\"",
    "\"END_PRINCIPAL\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<NUM>",
    "<FLOAT_NUM>",
    "<LETRA>",
    "<TIPO>",
    "<OPERADOR_MATEMATICO>",
    "<OPERADOR_LOGICO>",
    "\"@{ \"",
    "\" };\"",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<FOR>",
    "<TO>",
    "<DO>",
    "<HERDA>",
    "<RETURN>",
    "<CLASS>",
    "\", \"",
    "\",\"",
  };

}
